import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  // `docs/.astro` is generated by Astro on every build; linting it reports on
  // code nobody in this repository wrote.
  { ignores: ['dist', 'src-tauri/target', 'docs/dist', 'docs/node_modules', 'docs/.astro'] },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    plugins: { 'react-hooks': reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },
  {
    // Build and check scripts run in Node, not in the webview. `tools/` also
    // evaluates code inside a browser page, so it needs both sets.
    files: ['tools/**/*.mjs', 'docs/**/*.mjs', '*.config.js'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.node, ...globals.browser },
    },
  },
)
