//! Drafts that have no file yet, and survive being closed anyway.
//!
//! `Ctrl+N` opens a tab with no path — a notepad in the literal sense, which is
//! what a person reaches for when they want to put three lines somewhere before
//! deciding whether the three lines matter. The awkward part is that such a tab
//! has nowhere to be saved, so closing the window would throw it away, and a
//! notepad that throws away what you typed is not one.
//!
//! So the text is kept in the application's own directory, beside the settings
//! and never in the vault (ADR 0003). One file per draft, named by the tab's own
//! key; the tab knows nothing about where it lives, and a draft saved to a real
//! file has its scratch removed in the same step.
//!
//! This is not a crash-recovery journal for *named* files. A file that has a
//! path is saved by saving it, and pretending otherwise would put a second copy
//! of every note in `%APPDATA%` — a second truth for a product whose whole
//! promise is that the file on disk is the truth (ADR 0002).

use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// One unsaved draft: its text and the key it is filed under.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Draft {
    /// Identifies the draft across runs. Generated by the core, opaque to the
    /// frontend, and used as the file name.
    pub key: String,
    pub text: String,
}

#[derive(Debug, thiserror::Error)]
pub enum ScratchError {
    #[error("{0}")]
    Io(#[from] std::io::Error),
    #[error("this platform has no application data directory")]
    NoDataDirectory,
}

/// Where drafts live: a folder beside the settings file.
fn directory() -> Result<PathBuf, ScratchError> {
    dirs::config_dir()
        .map(|base| base.join("scheda").join("drafts"))
        .ok_or(ScratchError::NoDataDirectory)
}

/// A key that is a legal file name and unique enough for a folder of drafts.
///
/// The clock plus a counter: two drafts opened in the same millisecond are
/// ordinary (`Ctrl+N` twice), and a collision would silently make them one
/// draft.
fn new_key() -> String {
    use std::sync::atomic::{AtomicU64, Ordering};
    static COUNTER: AtomicU64 = AtomicU64::new(0);

    let millis = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis())
        .unwrap_or(0);
    format!("{millis}-{}", COUNTER.fetch_add(1, Ordering::Relaxed))
}

/// Writes a draft's text, giving it a key if it has none yet.
///
/// Returns the key so the tab can keep using it. An empty draft is not kept:
/// a blank tab is a placeholder, and filing it would mean every `Ctrl+N` that
/// was closed unused left a file behind forever.
pub fn keep(key: Option<String>, text: &str) -> Result<Option<String>, ScratchError> {
    let directory = directory()?;

    if text.is_empty() {
        if let Some(key) = key {
            discard(&key)?;
        }
        return Ok(None);
    }

    std::fs::create_dir_all(&directory)?;
    let key = key.unwrap_or_else(new_key);
    // Written whole and atomically, like the settings: a draft truncated by a
    // power cut is the one thing worse than no draft, because the tab comes
    // back looking intact.
    let path = directory.join(format!("{key}.md"));
    let temporary = path.with_extension("md.tmp");
    std::fs::write(&temporary, text.as_bytes())?;
    std::fs::rename(&temporary, &path)?;
    Ok(Some(key))
}

/// Removes a draft — it was saved to a real file, or closed on purpose.
pub fn discard(key: &str) -> Result<(), ScratchError> {
    let path = directory()?.join(format!("{key}.md"));
    match std::fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error.into()),
    }
}

/// Every draft left over from a previous run, oldest first.
///
/// Oldest first because the keys begin with a timestamp, and a person who left
/// three drafts open expects them back in the order they made them. A file that
/// cannot be read is skipped rather than failing the lot: one unreadable draft
/// should not cost the other two.
pub fn restore() -> Result<Vec<Draft>, ScratchError> {
    let directory = directory()?;
    let Ok(entries) = std::fs::read_dir(&directory) else {
        return Ok(Vec::new());
    };

    let mut drafts: Vec<Draft> = entries
        .flatten()
        .filter_map(|entry| {
            let path = entry.path();
            // `.md.tmp` files are a write that did not finish; the `.md` beside
            // them is the one that did.
            if path.extension().and_then(|e| e.to_str()) != Some("md") {
                return None;
            }
            let key = path.file_stem()?.to_string_lossy().into_owned();
            let text = std::fs::read_to_string(&path).ok()?;
            Some(Draft { key, text })
        })
        .collect();

    drafts.sort_by_key(|draft| sortable(&draft.key));
    Ok(drafts)
}

/// A key as (timestamp, counter), so `9-1` sorts before `10-0` rather than
/// after it the way a string comparison would have it.
fn sortable(key: &str) -> (u128, u64) {
    let (millis, counter) = key.split_once('-').unwrap_or((key, "0"));
    (millis.parse().unwrap_or(0), counter.parse().unwrap_or(0))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn keys_sort_by_time_then_by_counter() {
        // The string order would put `10-0` before `9-1`, which reverses two
        // drafts made a second apart.
        let mut keys = ["10-0", "9-1", "9-0", "100-0"];
        keys.sort_by_key(|k| sortable(k));
        assert_eq!(keys, ["9-0", "9-1", "10-0", "100-0"]);
    }

    #[test]
    fn a_key_is_a_legal_file_name() {
        let key = new_key();
        assert!(!key.is_empty());
        assert!(
            key.chars().all(|c| c.is_ascii_digit() || c == '-'),
            "“{key}” has to be usable as a file name"
        );
    }

    #[test]
    fn two_keys_in_a_row_differ() {
        // Two `Ctrl+N` presses land in the same millisecond, and equal keys
        // would make the second draft overwrite the first.
        assert_ne!(new_key(), new_key());
    }
}
